### ISSUE TITLE
Add "OC" Power Mode in addition to Lite, Medium and High Power Mode of rig manger  

### ISSUE THREAD

**Issue by BluefireXD** [nicehash/NiceHashQuickMiner#115]
Hello, I figured out that I cannot switch back to the Auto Tune OC settings if I switched the power mode in rig manager for ex. to medium. The only solution I found is to set power mode in rig manager to "Manual" and then restart quick miner so it loads saved autotune oc settings from commands.json. 
I think the same issue will happen if overclocking in classic mode is used (won’t change back to this settings)

I would suggest adding a new power mode (like “OC”) so that the users can load their own preferred oc settings too. (for ex. from auto tune). Means selecting “OC” Power Mode will do the same as if I restart quick miner and it loads the auto tune oc settings which I saved in commands.json bevore 

By the way. Is there a wiki/doc about this commands.json? would be nice to know how to modify this file 😊

**Comment by nicehashdev** [comment]
Manual mode already **IS** your custom OC mode. Your custom commands.json settings are applied if you have Manual mode selected. Therefore there is no need for extra mode.

**Comment by BluefireXD** [comment]
Yes this I thought too and also tested it before but it’s not working.
For ex.: 
1.) Start/Restart Quickminer -> Loads saved configurations (if "Manual" mode is preselected in rig manager)
2.) Switch to "Lite" mode in rig manager  -> Works fine a sets lower Power Limit, clock speed etc.
3.) Switch back to "Manual" mode in rig manager -> Doesn’t load saved auto tune configs, it only resets standard clock speed of the graphics card and also sets 100% power limit. 
4.) Restart Quickminer (like in step 1) and it loads my saved configurations (from auto tune) again.

So somehow, switching back to "Manual" mode does not load the saved configurations. 
Idk. Maybe it’s a bug in v.0.3.2.7RC

**Comment by nicehashdev** [comment]
I know this does not work, because it wasn't implemented to be used that way.

Is there any particular reason you would like to switch between modes?  If you ask me, a miner only wants to get perfect, most efficient settings. Once this is achieved, there is no reason to switch between, except when you go into the game (for this purpose, we made Game Mode).

To tune your card, you have following options with NiceHash QuickMiner:
1. Use OPTIMIZE button and tune your card with one click.
2. Use OCTune and only set your memory clock, find best max core clock limit with AutoTune.
3. Use OCTune and use alternative overclocking, manually setting memory clock and max core clock limit.
4. Use OCTune and use classic overclocking, manually setting core clock delta, memory clock delta and power limit.
5. Do not use OCTune but use some 3rd party OC tool such as MSI Afterburner (not recommended).

You choose one of the methods above and once you are done tuning, you just leave it and let it mine. Don't waste your time dealing with it. That is the whole point of QuickMiner - to save your time.

**Comment by BluefireXD** [comment]
Ok, yes I understand. 
But for ex.  while I’m working (like having an online meeting) I would like to reduce the fan noise of my pc. In this case I switch to "Lite" mode which is quiet. After the meeting/work I switch to medium and if I’m not in the room, sleeping, etc I would switch back to manual mode (OC mode) for max profit (but loud fans).  

"I know this does not work, because it wasn't implemented to be used that way." -> Is it maybe possible to add something like "CustomOC" Mode or  maybe make "Manuel" load the saved OC configs?

**Comment by nicehashdev** [comment]
We have plans for much more features and control over Rig Manager in the near future. It will be something in a form of ability to create own profiles and apply them. So, just wait a bit.

**Comment by BluefireXD** [comment]
wow, that sounds great! Good work! :)

Then i have to wait^^ Should I close the issue?
