### ISSUE TITLE
Nicehash.com only shows one rig

### ISSUE THREAD

**Issue by kindaran** [nicehash/NiceHashQuickMiner#116]
Two machines using 0.3.2.6. On https://www.nicehash.com/my/mining/rigs only one machine shows up when in Rig Manager view. Rigs mining also only shows one rig. If I refresh the page, the page will change between which rig is the only one showing up. Not entirely sure if mining for both is being accepted by the system. But when I click History & Stats > Active Workers > DaggerHashimito the accepted speed looks like two systems combined so hoping at least I'm getting mining credit.

![image](https://user-images.githubusercontent.com/65048254/109370416-6ebb6a80-785d-11eb-91e7-4eb4ba9a358a.png)

**Comment by nicehashdev** [comment]
Did you actually make installation on both rigs or you copied whole NiceHash QuickMiner folder with all config from one machine to another? If you did the second, then make reinstallation on one of the machines at least or delete nhqm.conf file. Or you can also change "uniqueID" to null for at least one of the rigs (you can find it in nhqm.conf file). The issue is that, because you copied whole folders including configs, both rigs got same ID, which is not allowed. By deleting set ID, you will force one of them to regenerate new uniqueID which will fix the issue.

**Comment by kindaran** [comment]
Lol, I did copy from one to another. I did change the "rig name"? in the config. I'll review your suggestions.

**Comment by kindaran** [comment]
Just confirming the following:
* stopped Nicehash on machine x
* modified config to set uniqueID to empty string
* exit Nicehash
* start Nicehash
* new uniqueID generated and now see two rigs online.
Thank you
