### ISSUE TITLE
Hotspot/vram temperature question

### ISSUE THREAD

**Issue by db-M-db** [nicehash/NiceHashQuickMiner#135]
Hello,

I noticed the new temperature (Vram temp) being reported in Rig Management.
In OcTune it gets reported as HotSpot.
In the latest releasenotes, you put "Added reporting of hotspot (vram) temperature"

But aren't Hotspot temp (which i believe is the hottest spot on die?) and Vram temp (which is the max/avarage temp of memory?) two completely different readings?
I'm confused...

I have an RTX 3070 and i thought these didn't have a vram temp sensor.
Can i trust that vram reading that is being reported?

**Comment by nicehashdev** [comment]
There are 8 additional temp sensors and these temps can be read. What these are exactly, I honestly do not know, because getting them is part of private NVAPI. If you have more information about that, please share it. We will rename these for cards that are not 3080, 3090 or TITAN RTX to HotSpot just like GPU-Z reports them.
