### ISSUE TITLE
issue with auto location selection

### ISSUE THREAD

**Issue by fentz** [nicehash/NiceHashQuickMiner#197]
version: 0.4.1.3

a) even if i choose not to use the auto location selection, the features is chosen (on config -1 is written on the specific field)

b) Also when i choose to use the auto location selection, the program does not work correctly. Rig is running at Athens(GR) and the program connects to USA for some reason. Also it chooses North EU for some little time. The correct location is West EU with the lowest ping!

Thank you and sorry for my english

**Comment by nicehashdev** [comment]
You need to wait about 10-15 minutes so that all locations are tested properly. Do not interfere with this process. After test is complete, best location with lowest latency would be selected.

When you want to change config, turn miner off, make the change and then start it up again. It could be possible that you were making change in the middle when NiceHash QuickMiner was also writing to the config file.
