### ISSUE TITLE
Wrong default memory clock on RTX 3090

### ISSUE THREAD

**Issue by Arvenies** [nicehash/NiceHashQuickMiner#206]
When using NHQM and excavator with default setting without any tune or OC the memory clock on RTX 3090 is set at 1188MHz (9501MHz), not the card default of 1219MHz (9751MHz) used in regular 3D workloads. So excavator uses RTX 3080 defaults on RTX 3090 as well, but RTX 3090 have higher defaults. This way all delta clock of memory is wrong calculated, because it counts from 9501MHz base, not correct 9751MHz base.

**Comment by nicehashdev** [comment]
Mining is performed in P2 state and not P0 performance state. There is not much difference but memory clock - which is for 200 MHz less in P2 state. That is why you see 9501 instead of 9751. It is possible to force CUDA workloads to be performed in P0 state (use tool such as nvidia inspector), but according to my tests, besides 200 MHz higher memory clock, there is not much difference and not worth the trouble. Because of different memory speed, you need to be careful when applying OPTIMIZE if you force P0 state - too high memory can crash your driver/card because it is effectively 200 MHz higher than expected.
