### ISSUE TITLE
Setup is not a setup file? NiceHashQuickMiner.exe

### ISSUE THREAD

**Issue by alexandreracine** [nicehash/NiceHashQuickMiner#214]
Can't install twice?

1. So I installed once by downloading, unzipping the files, and validate the CRC.
2. Restored + exceptions to the files in my AV.
3. Used "NiceHashQuickMiner.exe" to install in the folder C:\Program Files\NiceHash\NiceHashQuickMiner
4. Added an exception to that folder in my AV and copied the files "NiceHashQuickMiner.exe" and "excavator.exe" back from the unzipped folder.
5. Uninstalled from "apps" in Windows, without keeping any configs.
6. Used "NiceHashQuickMiner.exe" to install again, but this time there is no setup, it just want my NiceHash Mining Address.

Just a suggestion, but it would be nice if  "NiceHashQuickMiner.exe" would be an actual installer... or I am missing something.

This should go in the SUGGESTION box :) Thanks.

**Comment by nicehashdev** [comment]
NiceHashQuickMiner.exe works as a watchdog (or main program) and as an installer. We are trying to keep minimal amount of executable files due to insane amount of unjust false positive flagging from AntiVirus (AV) software vendors. Every additional executable thus brings a lot of work when trying to whitelist it and remove false positive flag.

NiceHashQuickMiner.exe starts as a main program when all the necessary files are present in working directory. If any of these are missing, it would turn itself into installer and offer you installation. According to your step 2, I would guess that your AV deleted one of the files (most likely excavator.exe) and then turned NiceHashQuickMiner.exe to become installer.

**Comment by alexandreracine** [comment]
Thanks for the details.
