### ISSUE TITLE
How to optimize for silence?

### ISSUE THREAD

**Issue by stillhart** [nicehash/NiceHashQuickMiner#215]
Hi

Is there a way or setting to optimize for silence? I would like to be mining but to limit the hashrate to a comfortable level for my ears.
Differently said, how can I tune for a custom max fan rpm instead of maximum performance or efficiency?

**Comment by nicehashdev** [comment]
No, not yet. But you can create your own fan rules and own OC profile using OCTune. Additionally, you will probably need to modify commands.json. Extra (incomplete documentation is here: https://github.com/nicehash/excavator/tree/master/api).

**Comment by MrX101** [comment]
On this, any plans to add a way to limit gpu useage to a set percent? I just want to avoid the chance of the gpu breaking due to constant 100% usage for long periods(even with low temps). I tried setting power limit to very low values, but it wouldn't reduce it below 100W(I have 1080)

**Comment by nicehashdev** [comment]
This is unfortunately not possible. GPUs are not like CPUs. Whenever you give GPU some task to perform, it would do it with full speed (with restrictions considered such as max clocks and max power). You can without any fear mine 24/7 for years using Lite optimization and hardware would still survive - we have tuned it that way, so rest assured, you don't have to have any fear.  This is valid for desktop GPUs only, not mobile! We don't know what happens with laptops if mining for long time because it wasn't done before in the history.
