### ISSUE TITLE
4.1.3 underclock on RTX 3090

### ISSUE THREAD

**Issue by lotharmatheos** [nicehash/NiceHashQuickMiner#219]
Undervolt core voltage setting not working, both classic and alternative
GPU-Z shows still 0,731V during mining
Afterburner not running
drivers 461.81
card MSI RTX 3090 Gaming X Trio 24G

**Comment by nicehashdev** [comment]
Unfortunately, that is minimal voltage. You cannot go below this voltage. Undervolting Ampere cards is useless, because there must be something more - the performance would fall down if there is too low voltage regardless of clocks which does not make sense. It is possible that clock reporting is not accurate. Since getting/setting is all part of private NVAPI, currently I don't have more information regarding that.
