### ISSUE TITLE
Automatically stop mining if the device has been thermal throttling for x minutes

### ISSUE THREAD

**Issue by borisdamato** [nicehash/NiceHashQuickMiner#265]
Excavator is aware of the gpu thermal throttling status as it prints a warning in the console when it happens.
I think it would be useful for it to stop automatically if it detects a thermal throttling situation has been ongoing for x (configurable?) number of minutes. This could be due to the room temperature increasing too much for instance.

It would be even better if it could send a notification to the nicehash mobile app to inform users of what happened, although I understand this would involve a lot more pieces than just stopping locally, but could be a good next step.

**Comment by cabe1214** [comment]
what about reducing the memory clock to a specific value if the GPU is thermal throttling, and reset it after X secs to the original high value? I guess this might be the best action until the room temperature is back to normal

**Comment by borisdamato** [comment]
> what about reducing the memory clock to a specific value if the GPU is thermal throttling, and reset it after X secs to the original high value? I guess this might be the best action until the room temperature is back to normal.
> 
> If **max_minutes_gpu_thermal_throttling** reached
> then reduce **MemClock** to **safe_mem_clock** for **minutes_until_mem_clock_restored**

Yes this would also be a good solution, or maybe even something similar to Autotune, in a sense that it could automatically start decreasing the memory clock until it reaches a value that lowers enough the temperature, that way it could be dynamic and safer in case for some reason even the  set **safe_mem_clock** isn't enough

**Comment by nicehashdev** [comment]
What you are doing now is what NiceHash had planned and coding in motion for past months already - scriptable mining where you can basically script out any scenario you want, but the project was put on hold because of recent dominance by ETH and we just did not see much of an use of scripting if there is only one algorithm. Contrary, when there are more algorithms, scriptable mining is probably the only reliable way to implement optimized mining (overclocks) with algorithm switching, because there are so many things that need to be taken care of.

GPU already reduces clock when thermal throttling - that is internal mechanism of the GPU to protect itself from being damaged due to heat. So, it is nothing wrong if GPU starts thermal throttling - it is actually good, you know that it works and you know that your GPU will survive. There are no dangers when this happen. It can also last for hours or days and will not damage the GPU. The problem would be if this mechanism fails, but in that case, your GPU is instantly dead and no notification helps you.

NiceHash already had high temperature notifications (just like rig offline) which are currently in maintenance and will be soon available soon. You can use these notifications to get informed if one of your GPUs cooling mechanism fails. There is no need for any extra feature regarding this in NiceHash QuickMiner. So this feature will not be implemented.
