### ISSUE TITLE
max core voltage option seems to be unstable

### ISSUE THREAD

**Issue by UnPure** [nicehash/NiceHashQuickMiner#270]
I tried using the `Classic method` on OCTune and set my cards to

- 3080 - C: 1410, M: 800, PL: 254, mV: 725
- 3070 - C: 1005, M: 1400, PL: 140, mV: 769

In general it seems to work but monitoring the voltage through HWiNFO64 it seems that sometimes the voltage still spikes back to higher values. The highest recorded voltage on my 3080 is `1.063` and on the 3070 it is `1.081`. Is this a normal behavior, is there a bug in OCTune or is something wrong with my settings?

QuickMiner is running on v0.4.3.1 RC

**Comment by nicehashdev** [comment]
Does the spike happens when DAG is being generated? Then this is normal, because OC is reset during DAG generation so DAG doesn't get corrupted.

Enable full detailed logging and logs would show whether this is something Excavator changes periodically to cause spikes or something that happens in the driver by itself.

**Comment by UnPure** [comment]
Yes, that seems to be the case. I stopped and started and it spiked up and went back down. I'll keep an eye on it while its running for a while to see if it stays stable. The DAG should only be generated once at the start, right? Are there any situations where it needs to be re-generated while its running?

**Comment by nicehashdev** [comment]
Yes, anytime your rig gets swapped to an order with different DAG, then DAG gets regenerated. So it can happen here or there.
