### ISSUE TITLE
Excavator closes afters few minutes

### ISSUE THREAD

**Issue by iKlepto** [nicehash/NiceHashQuickMiner#286]
I used the quickminer for few weeks without problems, but now it started to close after only few minutes running.
I have a GTX 1660

Here the message in the console
![image](https://user-images.githubusercontent.com/59902040/112737975-99bcdb00-8f3d-11eb-9315-fdfd8c814163.png)
and the log [exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6217295/exported_logs.zip)

**Comment by kirashi3** [comment]
Same problem here with an RTX 2060 card that has been mining just fine for the past 2-3 weeks. After over 15+ automagic restarts of Excavator it finally accepted a share for mining and I am back in business.

I've attached my **[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6216742/exported_logs.zip)** to help the devs understand what's causing Excavator v1.6.7c to open and begin grabbing jobs prior to restarting on its' own.

**If this is by design,** I would highly recommend the developers include further debug logging directly in the Excavator console so users know that the automagic restarts are _supposed_ to happen.

**Comment by nicehashdev** [comment]
Please, try latest [v0.4.4.0](https://github.com/nicehash/NiceHashQuickMiner/releases/tag/v0.4.4.0_RC) and see if it is any better.

I was already solving an exactly the same issue - it turned out that there was some 3rd program running which was making GPU very slow and the GPU was unable to create DAG in the given default time (45 seconds). Restart of Excavator follows, which is the default error handling mechanism.

I would suggest you to check out which other programs are consuming your GPU power and shut them down.

**Comment by iKlepto** [comment]
Oh, I dont know what worked to solve my problem but i had restarted my NVIDIA Drivers via OC Tuner, and reset my MSI Afterbuner configs at the same time and now the excavator is working.

**Comment by kirashi3** [comment]
> the GPU was unable to create DAG in the given default time (45 seconds). Restart of Excavator follows, which is the default error handling mechanism.

Thanks for the information and recommending we update - I'll update later this evening to see if the new version helps at all.

For the record, my GPU was **not** being utilized whilst I was attempting to start Excavator.

Also for the record, the console output should indicate the reason for Excavator's restart.
