### ISSUE TITLE
The hashrate on the RTX 3090 and GTX 1080 Ti differs from the calculator by about 10 MH/s

### ISSUE THREAD

**Issue by Yuranka** [nicehash/NiceHashQuickMiner#337]
Hello everyone! As recently it became known great news that finally added optimization for 1xxx series GTX graphics cards and I was finally able to optimize the second video card, but here's the problem, instead of the stated RTX 3090-120 Mh/s and GTX 1080 TI-46 Mh/s I get on RTX 3090 - about 105-112 Mh/s, and on GTX 1080 Ti - 39-42 Mh/s, although a little short of the required, but still a shame, because I lose almost as much as 10 Mh/s! I do not use any third-party programs for overclocking such as MSI Afterburner, I used only High optimization from NiceHash on NiceHash Quick Miner, tell me how you can fix this problem.
![bandicam 2021-04-02 18-49-43-702](https://user-images.githubusercontent.com/81821208/113519461-0adf3c80-9595-11eb-88a8-6649868f510c.jpg)

**Comment by nicehashdev** [comment]
Read this and also next question: https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ#faq07

Reaching speeds stated in calculator is possible but with appropriate conditions. When it comes to RTX 3090 this means having VRAM cooled down (below 90 helps a lot, under 80 is much better). Properly cooled VRAM on RTX 3090 with High OPTIMIZATION profile will give you almost 122 MH/s.

When it comes to GTX 1080 Ti - the data from calculator is a bit old - currently, GTX 1080 Ti can reach between 43-45, depending how far you push it. The problem is that the Pascal architecture is severely limited by the memory addressing reach of TLB - which is in Pascal only 2 GB. This means that with each additional DAG (increased size of DAG every 3/4 days), maximal possible speed is reduced a bit. If you set OPTIMIZE to Medium, you will get 43-44 MH/s, again, depending how cool you run the card.
