### ISSUE TITLE
Dual GPU Not Applying Settings to Second GPU[BUG] 

### ISSUE THREAD

**Issue by Vinasis01** [nicehash/NiceHashQuickMiner#345]
**Describe the bug**
I had in my system before 2x RTX 3080 and both were delivering 95 mh/s which is ok, swapped 1x 3080 with a 3070 and ran quick miner but the oc settings were not applied on the 3070 and it was pulling 195+ watts, tested with normal nicehash miner and applied the oc settings via afterburner and i was getting 95 on the single 3080 and 60 on the single 3070.

tested 2 versions of quick miner to be sure.

**To Reproduce**

**Expected behavior**

**Screenshots**
https://i.imgur.com/aE6VYgV.png

**Version affected (please complete the following information):**
 - Currently on Excavator 1.6.12a
 - RC or STABLE? Tried both.

**Additional context**

**Comment by nicehashdev** [comment]
Overclocks and optimization profiles are linked with GPU's serial IDs. This prevents misconfiguration of GPU with inappropriate OC values when swapping GPUs.

This means that when you swap GPU, you need to go through process of setting OC values or OPTIMIZE profile as if there was no GPU in before at that slot. This is not a bug but a feature and it has to work like that by design.
