### ISSUE TITLE
[BUG] Unmanaged Rigs

### ISSUE THREAD

**Issue by zerovski** [nicehash/NiceHashQuickMiner#369]
All my rigs appear as "Unmanaged". This means i can't use the optimizations profiles.

 - Version number 0.4.5.5
 - STABLE
 - Windows 10 Pro

Geforce GTX 1080 with 8GB. Connected to the motherboard by PCI.

I double checked and the address matches 100%.
I use NHQM since day 1, and it always showed my rigs as UNMANAGED. I was not worried because initially my gfx card was not supported by the optimization profiles. But with the latest NHQM it is, so i thought it was strange.

It's the second time i report this issue. The first time, it was closed by the dev without being solved...

[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6287904/exported_logs.zip)

**Comment by nicehashdev** [comment]
Did you resolve any issues with your AV?

**Comment by zerovski** [comment]
I don't have issues with my AV. That was another user.

**Comment by nicehashdev** [comment]
Do you still have this issue with latest RC version?

**Comment by zerovski** [comment]
I'm still using the latest stable version. Do you want me to try the latest RC?

**Comment by nicehashdev** [comment]
Yes, try it and report what happens. If you still have same issue, mind if you share your BTC Miningaddress here so we can see what is happening? Most likely must be backend related, because your log file looks fine.

**Comment by nicehashdev** [comment]
Yes. If you feel uncomfortable giving BTC over here, you can submit ticket with NiceHash, but that may take longer to get resolved.

Another quick test you can make is to open new account and reinstall putting in new address. If your rig still stays unmanaged, then the issue is on your side.

I hope you are aware that some AVs block QuickMiner even after you disable them (webroot for example).

**Comment by zerovski** [comment]
No, i'm ok with giving my mining address here: 39GggP153vQ5edCbeTC8Rvc6z8DYY9YMeh
I use the AV integrated with windows, where i allowed QuickMiner to run.

**Comment by nicehashdev** [comment]
I got info back that this BTC address wasn't connected ever. Please, double check your connection. Make sure this is the address you are using and turn on logging and submit logs again. Thanks!

**Comment by nicehashdev** [comment]
Yes please, submit logs (I need it from startup of app on, so I see how your domain gets resolved).

**Comment by zerovski** [comment]
Hi!
See if this covers what you need.
Thank you!

[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6345712/exported_logs.zip)

**Comment by nicehashdev** [comment]
Indeed, there was an issue on backend. Restart NHQM and you should be good now.

**Comment by zerovski** [comment]
Yes, it is ok!
Thank you very much!

**Comment by phonesuthat** [comment]
I have the same issue. Unmanage. I delete RIG several time and restart many time Problem still exist.

**Comment by phonesuthat** [comment]
[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6365134/exported_logs.zip)
Here is the log

**Comment by bruinxiong** [comment]
Hi, I met the same issue. One rig is still unmanaged. I try to reinstall the stable and RC version, respectively. However, this issue is still there. This is my log fil
[excavator_log_2021-12-05_07-47-57.000.txt](https://github.com/nicehash/NiceHashQuickMiner/files/7654979/excavator_log_2021-12-05_07-47-57.000.txt)
e.
