### ISSUE TITLE
[BUG]  0.5.1.3 crashes system when it loads. how to roll back to 4.5.5

### ISSUE THREAD

**Issue by BurrCheese** [nicehash/NiceHashQuickMiner#428]
**Describe the bug**

**To Reproduce**
As soon as I load the quickminer my system crashes and I have to manually reset.   I tried setting cards to stock, updating drivers
0.4.5.5. was stable how do I roll back

**Expected behavior**

**Screenshots**

**Version affected (please complete the following information):**
 - Version number [e.g. 0.4.5.5]
 - RC or STABLE? STABLE 0.5.1.3

**Hardware**
Describe GPUs used and how are GPUs connected to the motherboard.
DUAL 3090'S

**Logs**
Activate logging first, then record event - bug - then export logs into a .zip file and attach it when submitting this issue.

**Additional context**

**Comment by nicehashdev** [comment]
Please, try to update driver version to 466.11 non-DCH.

Old version is available on the first page.

**Comment by BurrCheese** [comment]
Thank you for the reply.I was able to find the old version and now that is crashing on load as well since the initial update.I see two drivers on the Nvidia page. Studio 462.31 and game ready 466.11No luck with the game ready. I will try studio. I ran furmark stability tests on both of my graphics cards and they are stable and error free. Not sure what's going on. Sent from Android deviceOn Apr 21, 2021 4:39 PM, djeZo ***@***.***> wrote:
Please, try to update driver version to 466.11 non-DCH.
Old version is available on the first page.

**Comment by renedx** [comment]
We’ve updated drivers to 466.11, latest windows updates and 2 rigs keep crashing as soon as NHQM starts. Zero logs to be found as the PC just reboots.

Tried reset optimize and didn’t work either. I’m thankful there is a stop button otherwise the pc would be crashing and rebooting for life.

The only difference these rigs have versus the others who do run, is that they do not have sufficient memory and use disk / swap to “fix” this. Besides that these 2 rigs are all gigabyte 3080 cards, the other rigs are all MSI & Asus 3080 cards.

I’ll be trying windows update revert later today. As the older version of NHQM currently crashes too, so it seems to be something related to either the windows updates or driver updates.

**Comment by nicehashdev** [comment]
Do you still have issue with this?

**Comment by BurrCheese** [comment]
It's been stable the last few days since I did the driver clean install, set the swap file to 20gb, and set the optimization profile to medium.I'm still running 4.5.5. I have not attempted to update to 0.5.1.3Sent from Android deviceOn Apr 25, 2021 12:25 PM, djeZo ***@***.***> wrote:
Do you still have issue with this?

**Comment by nicehashdev** [comment]
I am closing this issue. If you have problem again. Open a new issue.
