### ISSUE TITLE
[BUG] Webroot still kills NHQM and Excavator despite being whitelisted

### ISSUE THREAD

**Issue by Intoxicus** [nicehash/NiceHashQuickMiner#438]
**Describe the bug**

Seems to be common and well known.
Webroot ignores whitelisting and treats all crypto mining as malicious.

I've contacted Webroot on the phone and left a voicemail with a manager expressing concerns that they're driving away their target market by doing this.

If Webroot does not respond with something along the lines of "This is going to be fixed" I'll be finding another AntiVirus.

**To Reproduce**
 Use Webroot with NHQM whitelisted.

**Expected behavior**
It will randomly terminate the process presumably because Webroot flags all crypto mining as malicous.

**Screenshots**

**Version affected (please complete the following information):**
All versions it seems

**Additional context**
Should we start a list of A/V programs that don't treat regular crypto mining as malicious??

Webroot tech support is incompetent.
Despite being told that whitelisting is broken they keep telling me to whitelist NHQM. They don't seem to be very good at reading comprehension.

**Comment by Intoxicus** [comment]
It seems that Webroot will not be doing anything to fix this and they regard all crypto mining as malicious.
This is the email I got just a few minutes ago:

"
Support wrote:
Hi Graeme,

We will not be whitelisting this miner globally on our end. 

We have seen computers compromised by threat actors who have deployed these types of currency minors maliciously on computers/servers that don't belong to them, of which they don't have permission to install miners on. We are a security company, please understand that from our perspective we have to protect our customers from malicious actors deploying currency miners on their systems without permissions, regardless of the fact that other customers may be trying to use these miners intentionally. 

We understand you feel like we aren't addressing your issue, but we have requested multiple times that you call our support team so we can assist you with whitelisting the miner on your system, so that Webroot is no longer interfering with it. Other anti-virus companies are also going to present similar problems of flagging currency minters - this is why a lot of currency miners have dedicated systems which are not running AVs. The way forward is to get it whitelisted locally on your system with the proper configuration.

Please call us at 1-866-612-4227 during normal business hours. Webroot's Customer Support business hours are 7:00 am to 6:00 pm, MST, Monday through Friday. 

Regards,
The Webroot Support Team


 

To view the original ticket, you can log into your Webroot Console. To access your console, click the link below or copy and paste it into your browser:

https://mysupport.webrootanywhere.com/supportwelcome.aspx

You can reply to this message by replying to this email directly or from your Webroot Console.

Regards,
The Webroot Support Team
"

**Comment by Intoxicus** [comment]
Webroot is indeed flagging NHQM and Excavator as "malicious" and they seem to not want to be reasonable about this either.

What A/V out there is Crypto Mining Compatible?

![false positives](https://user-images.githubusercontent.com/28819288/115775291-f14d3b80-a36f-11eb-84fc-1f720e86e631.png)

**Comment by Intoxicus** [comment]
It appears that the files are being flagged as malicious by Webroot and the whitelisting is being ignored.
All the "infections" in the log are all NHQM related files that I've whitelisted.

Is there any A/V out there that doesn't treat any and all crypto mining as malicious?

![false positives IP redacted](https://user-images.githubusercontent.com/28819288/115775613-586af000-a370-11eb-945f-182569c535b9.png)

**Comment by nicehashdev** [comment]
This is not really bug of NHQM but webroot as you have figured it out on your own. Their reasoning logic why to keep it blocked is flawed - NHQM is not entry vector but some other malware - that malware should be blocked. However, blocking original malware is much harder, because it usually use anti AV techniques. NHQM does not use them so it can be easily targeted and blocked. Additionally to that, AVs also have massively bugged whitelisted features.

We will launch lawsuits against all the AV companies that are causing us damages with such ignorant lazy behavior.

**Comment by Intoxicus** [comment]
Wow, a lawsuit may just be what is needed if it can be viable.
I do get it from their perspective to a degree.
But when they know a specific program is a widely used and confirmed safe miner used by people to mine casually it's like they're giving their power users customer a middle finger for wanting to make some extra cash on the side.
Webroot is an extra frustrating piss off as they market to power users.
They're literally doing stuff that they should know is going to piss off their intended target market and then act they think we'll buy their scripted rhetoric.

In Canada you can probably file a complaint with the Competition Bureau Canada for anti competitive behaviour and false advertising.
By the "General Impressions Test" I would say I have the general impression AV are not supposed to be making me less secure by doing things that anyone with knowledge and experience in the field would not be impressed with.

Webroot's handling of this is literally and directly making me less secure.

**Comment by nicehashdev** [comment]
Exactly. An AV that starts using policy instead of technology to make decision whether piece of software is malware is not, is not AV you can trust to protect you, because you can never know when their decision making mechanisms is being “bribed” by someone to let certain harmful piece of code through and certain completely legit piece of code blocked, just because it is part of a competing software and it is actually far from being malware.

**Comment by KingNewbs** [comment]
> The way forward is to get it whitelisted locally on your system with the proper configuration.

Is it just me or is that letter from Webroot revealing that they either do not understand Intoxicus's request, or that the request was not explained well enough to them? It sounds like they are refusing to "globally whitelist" QuickMiner (which is, to be frank, a perfectly reasonable position) when the actual problem is that even when manually whitelisted, Webroot still quarantines / interferes with the process. 

I'm curious if you ever called the support number provided, Intoxicus? It sounds to me like they want to explain to you how to whitelist Quickminer yourself, which means either A) they don't understand what you're asking, or B) perhaps you have not whitelisted the process correctly, or there is some obtuse technique they need to walk you through?

**Comment by Intoxicus** [comment]
I did eventually call and it's convinced me to switch to a different A/V program.

They simply don't get it.

They don't seem to be able to understand what I am getting at.

They keep telling me to whitelist NHQM like they never even read what I wrote and assumed the what the problem is.

There is no obtuse tek, and it is as whitelisted as it could ever be. Literally every possible file and folder associated with NHQM I could whitelist is whitelisted.

In Canada you can file a complaint for false advertising and anti competitive behavior against Webroot with the Competition Bureau Canada(Canada's version of the FTC.) The way they market Webroot makes it seem like they wouldn't be one to be this kind of ridiculous(Look into the "General Impressions Test".)

Should we be making a list of A/V programs and how compatible they are with NHQM and crypto miners?
Potentially this can eventually sway some of them maybe if they realize all us power user miners are going to the crypto tolerant A/V program.

Or does someone need to start a new A/V that is crypto friendly?(Easier said than done, but there is a viable market I believe.)

I should not need to make myself more vulnerable to miner crypto because A/V companies are too lazy to differentiate between malicious use of miners and actual mining that is nothing to do with Malware.

Ultimately their laziness makes us all less secure. 
And I'm not paying them to be lazy and make me less secure...

**Comment by Intoxicus** [comment]
https://community.webroot.com/webroot-secureanywhere-antivirus-12/why-is-webroot-punishing-casual-crypto-mining-347210?postid=365735#post365735
