### ISSUE TITLE
GeForce RTX 3080 VRAM Temp dangerously high on LITE setting for Nicehash quickminer

### ISSUE THREAD

**Issue by blusave** [nicehash/NiceHashQuickMiner#443]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
Yes/No. NO

**Your question is...**
My VRAM temp is going between 104 and 108c on my new GeForce RTX 3080. The drivers are up to date. The VRAM temp stays this high regardless of whether I run it at lite setting or manual. Please let me know how to loser the max VRAMP temp which according to the site should max out at 96c

![Screenshot 2021-04-23 195030](https://user-images.githubusercontent.com/83104138/115944853-30ad8200-a46d-11eb-96b0-a8d53e5aabde.jpg)

**Comment by ironpossum** [comment]
@blusave you will need to manually lower the TDP target in the "OCTune" page in order to reduce power draw and thus heat. If you want to run at full mining potential, you will need to mod the card (at your own risk) with better thermal pads for the VRAM. Research your specific card before you do this. I'm not telling you to mod your card, I'm just letting you know that's what it will take if you don't want to reduce the TDP.

**Comment by blusave** [comment]
Thanks for the reply. I’m not qualified to mod the card. I’m just mining with my gaming computer when I’m not using it with the quick miner application. Would you be able to send me screenshots of how to tune the settings and to what values in the OCTune. Not looking for full mining potential- I just want to run at safe conservative settings. 

Thanks

**Comment by nicehashdev** [comment]
Unfortunately, these temperatures are by design from manufacturer and are considered safe all the way up to 110 C.

It you wish to reach lower temperatures, you will have to apply manual settings in OCTune.

We are working on another set of profiles (Quiet) that would reduce core clock (thus power and temperature) if breaching certain temperature. You can already utilize this feature manually in OCTune. Instructions are available in Wiki.

**Comment by alaa007** [comment]
You have to change the thermal pads with a decent brand like Thermal Grizzly for the vram and temp will go down to 80c. this issue is well known with founders edition and some other brands like Gigabyte.
