### ISSUE TITLE
[BUG] Quickminer overrides manual settings 0.5.1.3

### ISSUE THREAD

**Issue by joheiska** [nicehash/NiceHashQuickMiner#477]
**Describe the bug**
Quickminer 0.5.1.3 overrides manual settings set by MSI afterburner after 10-30 minutes of applying them. This causes higher power draw with zero improvement for hashrate as the card will run on higher clockspeed and voltage.

**To Reproduce**
1. Set optimizations to manual
2. Apply custom voltage curve/power limit/clockspeed settings with msi afterburner
3. wait 10-30 minutes
4. Quickminer overrides these settings and the clockspeed and voltage will increase

edit: also stop -> starting seems to reproduce this and make quickminer override the manual settings applied by msi afterburner.

This happens regardless of the computer being active/idle or monitors being on/off.

**Expected behavior**
To not override user specified settings (from another app) when everything is set to manual. 0.4.5.5 worked flawlessly and kept my own manual settings. Quickminer should not apply any "optimizations" when everything is set to manual.

**Screenshots**

**Version affected (please complete the following information):**
 - 0.5.1.3
 - stable

**NVIDIA driver version**
465.89

**Hardware**
3060 Ti, directly in x16 slot

![quickminer doing random stuff](https://user-images.githubusercontent.com/25272019/116634495-e3e21380-a964-11eb-92c3-dc59c5c04e95.png)

**Comment by alexandrefim** [comment]
same here...

**Comment by nicehashdev** [comment]
Try to add parameter `-g` to the extra launch command line parameters when launching Excavator. This will remove Excavator’s behavior of reducing memory OC during DAG generation.

Also, is there a reason why would you use Afterburner instead of OCTune? OCTune allows you to perform undervoltage as well and it is done with less trouble as you only enter voltage in mV and designated core clock. It is also fully compatible with Excavators _mem to 0 while gen DAG_ feature.

**Comment by joheiska** [comment]
> Try to add parameter `-g` to the extra launch command line parameters when launching Excavator. This will remove Excavator’s behavior of reducing memory OC during DAG generation.
Seems to work for the core clock, need more time to test though. Memory clocks not affected by this flag. Though I'm pretty sure that isn't working the way it is supposed to anyway. My cards memory clock is lowered by 200mhz allways, not just for DAG creation.

> Also, is there a reason why would you use Afterburner instead of OCTune? OCTune allows you to perform undervoltage as well and it is done with less trouble as you only enter voltage in mV and designated core clock. It is also fully compatible with Excavators _mem to 0 while gen DAG_ feature.


Because it's my preferred software. Better usability, better features, less bugs. Also I have afterburner running 24/7 unlike quickminer. Also like I mentioned before, quickminer has a tendency to lower memory clock when it is running (not just for DAG creation) by 200mhz. Might need another bug ticket for that...

This shouldn't be the point of discussion though. If you have manual option, it should mean that quickminer doesn't fiddle with the card in any way. You shouldn't force people to use quickminer OCTune.

Everything seemed to work properly with 0.4.5.5 so I don't really see the point of removing the bug label? The behaviour of quickminer changed in 0.5.1.3 (for worse).

**Comment by nicehashdev** [comment]
200 MHz lowering is due to P2 power state when card is being used for CUDA (compute) tasks. This is by design made by NVIDIA. If you wish to keep higher memory clock, then you can either overclock by 200 MHz or you can force P0 state for CUDA tasks (NVIDIA profile parameter which you can set with app such as NVIDIA profile inspector). It is much easier to simply overclock by 200 MHz because this breaks less things - many apps and OC profiles etc are already adjusted to this fact that CUDA tasks have lower memory base clock. This feature has nothing to do with Afterburner and Afterburner is not capable of adjusting this parameter (you need NVIDIA profile inspector).

Also, what Afterburner is lacking is ability to detect when memory clock needs to be reduced due to DAG generation so that DAG is valid and not invalid (high memory clock can cause mistakes when writing memory - GDDR6 and GDDR6X can run with higher speeds when being used for reading only and not writing). This thing alone should sway you towards OCTune as it allows you to run memory with much higher speed.

When it comes to mentioned bugs in OCTune - can you let me know what these are so I can fix them?

**Comment by joheiska** [comment]
> If you have issues, just continue using 0.4.5.5 - that version is solid, secure and doesn't have any performance improvements over 0.5.1.3 so if you are used to it, it is fine to continue using it. Let's hope that NVIDIA detects issues on their side and finally fixes their drivers for good.

I'd be happy to, but quickminer doesn't seem to have option to remove the annoying "do you want to update" popup on every startup. Could you at least make an option to remove this so people wont upgrade without a good reason?

**Comment by nicehashdev** [comment]
You can disable auto updater in config. bNoAutoUpdate is called I think.

**Comment by Intoxicus** [comment]
"YoU'Re ThE OnLy OnE tHaT hAs ThAt IsSuE.."
