### ISSUE TITLE
[QUESTION] 980ti support

### ISSUE THREAD

**Issue by Robert-Saiter** [nicehash/NiceHashQuickMiner#480]
Is there a reason the 980 ti isn’t supported but the Titan X is?  I believe it’s the same gpu and the 980ti has 6GB of memory which should be enough.  

I have several of these which I can use with the NH miner (a few plugins work with it) but having quickminer working would be ideal / more convenient for me.  Is there a technical limitation I am not aware of?

**Comment by nicehashdev** [comment]
Quantity of VRAM is not the only limiting factor. GeForce GTX 980 Ti is a Maxwell architecture (SM and compute 5.2). This architecture has TLB reach of only 1 GB (Pascal has reach 2 GB). This means that GeForce GTX 980 Ti would hash very slowly (approx, 2-3 MH/s) due to heavy TLB thrashing, which is kinda useless, because even CPU daggerhashimoto mining is faster then. GeForce GTX 980 Ti can earn you more if you use it to mine another algorithm with it. I hope this answers your question.

**Comment by Robert-Saiter** [comment]
Thank you! The TLB situation explains it completely, I overlooked the TLB size differences between the cards.   I appreciate the information.
