### ISSUE TITLE
[BUG] Crash unexpectedly - NHQM Case ID: 07cda515

### ISSUE THREAD

**Issue by JJMineTheGap** [nicehash/NiceHashQuickMiner#482]
QM keeps crashing and I can't seem to tune it to be more stable. I have the 3090's at med opt, the 3080's at lite. Logs attached. Also - it won't start the miner after a reboot until I log into windows, then it will start 15 sec later. Can it be setup to start on reboot, Before it logs in? I tried in scheduler but didn't work. Thanks.

Stable version 

**NVIDIA driver version**
461.92 - clean install, just the drivers

**Hardware**
risers
i7

**Logs**
Attached
[exported_logs_aftererrors.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6408585/exported_logs_aftererrors.zip)

**Comment by nicehashdev** [comment]
Regarding crashing: try to update drivers to the latest version. The version you use has turned out to be very unstable in my case.

Regarding autostart: this feature is not supported out of the box, because NHQM has UI which needs certain user logged in. There are several ways how to solve this issue but none of them is very good. You can start it as SYSTEM, but then you lose UI. You could also write pure commands.json on your own and let it autostart with Windows.
