### ISSUE TITLE
Is there any way to apply the OC profile repeatedly over time

### ISSUE THREAD

**Issue by 14kwanss1** [nicehash/NiceHashQuickMiner#492]
when i use task scheduler to start nicehashquickminer, it sometimes resets the OC settings.

My question is whether it is possible to edit the command.json file to apply the OC settings every set period of time

currently i have it as such:

	}, {
		"time": 30,
		"loop": 30,
		"commands": [{
				"id": 1,
				"method": "worker.print.efficiencies",
				"params": []
			}, {
				"id": 1,
				"method": "device.set.oc_profile",
				"params": ["GPU-777e869f-7a0e-56f9-5415-d22de906ac27", "-800", "-1000", "152"]
			}]

but this does not work as i intend it to when i test it. once the oc settings get randomly reset, it subsequently show that the oc settings in fact are not applied every 30 second.

btw as you can see from above i am intentionally underclocking my gpu because i put my computer in living room and i want it to be completely silent

Thanks in advance for any input or suggestion.

**Comment by nicehashdev** [comment]
Latest version should not lose OC settings - if it does, make sure to disable all other 3rd party OCing tools such as MSI Afterburner.

It is not recommended to have this in a loop, because change of clocks makes your GPU inoperable for several 10 ms (it is not working for that time) thus reducing speed of it. If you have to do it, do it with longer interval (5minutes at least, 300 seconds).
