### ISSUE TITLE
[BUG] nhqm.conf deleted content after unexpected reboot

### ISSUE THREAD

**Issue by Arvenies** [nicehash/NiceHashQuickMiner#503]
**Describe the bug**
When rig have unexpected sudden reboot (ex. power shortage, unstable rig), the file nhqm.conf get content deleted (exactly it gets 0 bytes in size), and when NHQM automatically starts after such reboot, it goes into "first start" mode and don't start mining.

**To Reproduce**
Suppose hard reset the rig. I noticed it 3 times, but this occur not every time.

**Expected behavior**
Content of nhqm.conf unchanged and continue of operation.

**Version affected (please complete the following information):**
 - first noticed with v0.5.1.3 if remember correctly
 - last notice with v0.5.1.6 RC

**NVIDIA driver version**
466.11 standard

**Hardware**
GPU or CPU doesn't matter in this case. Drive is SSD connected via M.2 slot.

**Logs**
Windows event log show unexpected system shutdown, so it wasn't standard system shutdown or reboot.

**Additional context**
Observed several times on every unexpected reboot starting with some version of QM. Earlier versions didn't have this problem.

**Comment by nicehashdev** [comment]
Set your HD in Windows to manage disk with no write cache - this will make such event very unlikely to happen.

**Comment by Arvenies** [comment]
Yest, this is some kind of workaround. On rigs dedicated for mining this is no problem, but on "everyday" PC this have a huge impact on performance.
Isn't it because of fact, that QM have this file open all the time because of setting bLastRunCrashed?

**Comment by nicehashdev** [comment]
If you have multiple HDDs, you can customize which one has write cache enable and which one doesn't. Put NHQM on disk with write cache disabled.

I will take a look what can be done in code to improve this situation - the issue is in general C# stupidity of doing write locks when just reading a file.

**Comment by Arvenies** [comment]
Unfortunately turning write cache did not help. Of course I restored nhqm.con from my backup, but it was lost in a reboot initiated by NHQM in the night, so rig did not mine for few hours. Below some info from logs:
`[2021-05-12 05:54:26:638] [INFO] [watchdog] Speed of device id #2 is 0 for long time, restarting...
[2021-05-12 05:54:26:639] [INFO] [watchdog] Trying restart first...
[2021-05-12 05:54:26:639] [INFO] [watchdog] Performing restart of Excavator
[2021-05-12 05:54:26:639] [INFO] [watchdog] Shutting down excavator.exe
[2021-05-12 05:54:46:653] [WARNING] [watchdog] Excavator shutdown timeout, rebooting rig`
And after this reboot content of nhqm.conf was gone.

**Comment by Arvenies** [comment]
Digging a little more in Windows Event Viewer it seems that NHQM initiated reboot, but it did not proceed clean. Less than a minute after above log form NHQM there is info in Event Viewer that last Windows shutdown was not clean. Nevertheless problem still exist even after disabling write cache.

**Comment by fynxer** [comment]
Just so you know I have the same problem on some rigs the last few weeks. seems to happen with unscheduled restarts probably by NHQM.

Suddenly i find that NHQM has gone into "first start" mode and don't start mining after restart.

Since the nhqm.conf is reset there is no BTC address in it, it says "null"

Why would NHQM in any way reset the nhqm.conf after restart so it stops working.

nhqm.conf should be locked down so it is always available when NHQM starts.

**Comment by tulup4ik** [comment]
get same issue couple of times too. not a general C# issue - hardcore developers is main cause of all nhqm bugs :\

**Comment by LukePoga** [comment]
i get this all the time. its pretty obvious what they are doing. writing to config while system crashes/reboots. pretty lame.
