### ISSUE TITLE
[FEATURE] Set CPU Power limits for windows when mining/game mode

### ISSUE THREAD

**Issue by SteadVex** [nicehash/NiceHashQuickMiner#533]
Is it possible to set Maximum Processor State as defined by Power Options within windows for game mode/mining?

I currently set my CPU to 99% when leaving the computer mining to prevent turbo being constantly active, it would be nice if this could be built into game mode and allow 100% for that and then rrevert back to what I want to set it to during mining.

![2021-05-21](https://user-images.githubusercontent.com/22118749/119201173-41f6a800-ba86-11eb-9861-4796378aea83.png)

**Comment by ironpossum** [comment]
@SteadVex I'm seeking to understand what you are trying to accomplish by preventing turbo/boost clocks in the first place. Are you trying to simply reduce power consumption? or are you thinking that it will just be "less stress" on your CPU and thus make it have a longer life? Some other reason I'm not thinking of? What is the root problem are you trying to address?

Here are some suggestions based on speculative answers: 
- If it's about CPU lifespan due to boost frequencies alone, this action isn't going to make a difference to the lifespan of your CPU.
- If you have thermal throttling occurring or are running at near-thermal throttle temps, then I can see your concern, in which case I would suggest improving your CPU cooling or instead try changing the CPU utilization target to reduce heat load. Instructions on how to change this setting here: https://www.reddit.com/r/NiceHash/comments/mlbdzt/cpu_mining_slow_with_quickminer/

**Comment by SteadVex** [comment]
@ironpossum 

Thanks for taking the time to respond!

Its not really a heat issue, for me its more noise and power consumption, I've enabled CPU mining just mining with it limited to 99% power results in a 50/60w power consumption vs 15/20w not doing mining but still having the GPU's mine, full turbo is 115 to 120w which seems a huge increase in power for very little gain.

If I'm honest day to day I can't tell any difference between the CPU running at 2ghz/3ghz/4ghz/5ghz so I just limit the max power so the noise doesn't annoy me when I'm working, just feels wasteful having a constant high power draw on the CPU for such little gain, I've worked out its less than 20% increase in work load for over double the power consumption

**Comment by ironpossum** [comment]
@SteadVex awesome - definitely check out the link I posted above. If you edit the config file you can specify a lower CPU utilization target, which means there should be lower power draw. Maybe try setting it to 50 or 25 and see what the results are and play with the number until you find what you're looking for. This should eliminate the need for you to change anything in the power profile and would also eliminate the need for this feature to be implemented. If this doesn't work I would be curious to know what happened.

**Comment by Dohtar1337** [comment]
We will investigate an option to add a "CPU limiter" feature where XMRig would limit the number of cores used when mining. Limiting amount of cores would also limit the load on the CPU. This feature might actually be also great for NHM.
