### ISSUE TITLE
Automatic start and stop depending on load

### ISSUE THREAD

**Issue by ebelanger** [nicehash/NiceHashQuickMiner#56]
I mine on my gaming rig and thus must stop the miner when I game and start it back when I stop.  This sometimes leads me to forget, losing on some mining time.

I was wondering if it could be possible with the information available to detect when the MH falls down because of external demand.  This could allow for setting a MH threshold that would stop the miner and restore the default OC tuning.

For detecting when to start, it could probably be done when GPU utilisation is low for a certain time.  The miner would then start back again.

Thanks for the great product so far :)

**Comment by nicehashdev** [comment]
This is on TODO and I am still investigating how to do this reliably enough as it is not so trivial.

**Comment by TerryFrench** [comment]
Complex: if excavator is taking most of your GPU memory, starting a game might fail due to not enough GPU memory. 
We could have a list of processes (as the miner runs as administrator) when a process starts, turn it off, but every game has a different process... 

Proposal: check how Windows 10 "Game Mode" works. I do turn game mode on before playing, and turn it off after playing. There might be a way to get a notification of the state of "Game Mode". That would be a good compromise I think, 

![Game mode](https://user-images.githubusercontent.com/5620841/108606223-aca42480-736d-11eb-8574-c0933fe65899.PNG)

**Comment by crafty35a** [comment]
> Proposal: check how Windows 10 "Game Mode" works. I do turn game mode on before playing, and turn it off after playing. There might be a way to get a notification of the state of "Game Mode". That would be a good compromise I think,

Very few people use game mode this way, and it's not even the intended way to use the feature. It defaults to being enabled, and when it's on Windows will automatically detect when games are running and attempt to boost performance. It isn't really meant to be manually enabled/disabled constantly.

**Comment by TerryFrench** [comment]
Good to know and unfortunate then.

**Comment by TerryFrench** [comment]
detecting the various game libraries launching processes: Steam, Epic, GOG, Origin, Battle.net is another option, but many will keep them running in the background when not playing.

**Comment by nicehashdev** [comment]
Feature is on todo list, closing issue.
