### ISSUE TITLE
Console App Source

### ISSUE THREAD

**Issue by LanceMcCarthy** [nicehash/NiceHashQuickMiner#67]
Hi team, thank you for putting together a signed and trusted version of this. 

Looking at the components, this appears to a .NET project (hurray!). However, is the actual console app open source? I'd love to donate some time and help out on any open issues.

I see some standard Win32 parts and it looks like a .NET Framework 4.5 to 4.8, but I think this should really be changed to a .NET5 console app, you will get _significant_ performance gains for free (see https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-5/).

Bonus: once you change project type to .NET5 you can run it on Linux and MacOS, too!

**Comment by nicehashdev** [comment]
[Excavator](https://github.com/nicehash/excavator) (the console app that you see) is not open source, it is written in C++ using boost, rapidjson and CUDA. It is a NiceHash's proprietary miner, entirely developed from scratch as an alternative to other devfee and open source miners. The existing open source miners did not have the flexibility of supporting multiple algorithms and multiple devices at the same time because they were all based on ccminer (which was based on cpuminer). So, we decided to make a brand new miner with algorithm switching capabilities in mind and the core of it heavily revolves around that idea. Unfortunately, we did not have enough resources (mainly human) to continue development in 2019 so the project was put on hold. But recently, due to the fact that there is mainly just daggerhashimoto (ethereum) algorithm paying well enough, we have restarted development of it. We would very much like to make Excavator open source, because we want to be fully transparent with this project and show that there is no malware hidden in it and using it pose **no security risk whatsoever**. The problem we have is that the mining community as shown in the past is extremely inclined towards stealing intellectual property for self monetary gains. That is probably one of the reasons why authors of devfee miners stay unknown and (almost) never reveal their identity. Doing so, would make them liable to lawsuits due to breach of open source miner's licenses. And of course, they do not want to reveal source of their miners (as specified by the miner's license) to hide the optimisations that make their miners faster. As it turns out, making an optimisation is much easier than writing whole miner from scratch. The fact that all publicly available miners originate from one single source proves this statement. If we made Excavator public, without a doubt, some devfee miners would use it as a codebase for their optimisations as it provides significant benefits in multialgo and multidevice environments.

Excavator is powerful, but not easy to use as it requires significant knowledge of it's [API](https://github.com/nicehash/excavator/tree/master/api) to manage it (either to write command files, or to command it over TCP or HTTP). Here comes QuickMiner (this project). It makes using Excavator extremely easy, provides important error handling and communication with NiceHash's Rig Manager so some remote commanding such as starting/stopping, setting optimization profiles and in the future, manual overclocks, is possible. We will probably make QuickMiner wrapper public. For anyone interested, C# code can be easily decompiled, so whoever is interested what is hidden inside, it is possible to do that now already. **We use no packers or protectors** - that would be contrary to the idea of transparency.

We guarantee that software made by us is actually made by us and malware-free with code signing certificates and providing [hash checksums](https://github.com/nicehash/NiceHashQuickMiner/tree/main/checksums). Only stable versions are signed, because signing takes same time and it would be impractical to sign all RC versions. The certificates are owned by H-BIT d.o.o. company, located in Slovenia, European Union. There are real people behind this project contrary to the devfee miners which are mostly unknown, heavily protected and pose serious security risk. We are well aware of this situation, especially now with the widespread mining. Only professional miners have specially dedicated mining systems, which, even if getting infected with malware, cannot cause any harm. But the majority of miners are mostly (occasional) gamers. They do not have special dedicated mining rig, but their own PC, which is most likely used for security-related tasks such as handling online payments, cryptocurrency wallet payments, having saved logins to various emails, social media accesses, etc.. A dedicated mining rig contains no information whatsoever, but gaming PC in modern times is a goldmine for hackers.

We have put increased effort in development of QuickMiner mainly because of security reason. We will shortly make a public announcement regarding this security threat to inform public better about the issue because we notice that the general awareness of this problem is very low.

**Comment by LanceMcCarthy** [comment]
I congratulate you on signing the stable builds. I know how difficult it is to get a cert from DigiCert (My software development LLC has both code sign and kernel mode code sign certificates from them and I know how thorough their vetting process is).

![image](https://user-images.githubusercontent.com/3520532/108611773-e138d000-73af-11eb-9dc0-e1b9691a2abc.png)

The only remain part to establish trust is to know who H-BIT d.o.o is. I have found them in an EU business directory and they indeed appear to have an established presence https://www.dnb.com/business-directory/company-profiles.h-bit_doo.3e3a946aff5c06a308a46871e26fbf63.html (As opposed to a 1-dev show who paid $500 for a d.o.o to pretend they are legitimate :))

You can close this Issue, thank you for the honest and thorough answer.
