### ISSUE TITLE
v0.5.3.0RC about 25% lower Hashrate on RTX3090

### ISSUE THREAD

**Issue by Killua-Zolldyck** [nicehash/NiceHashQuickMiner#713]
Hi folks,

On my RTX3090 using the same settings in v0.5.3.0RC as in version v0.5.2.0 stable (preset: MEDIUM) the hashrate has dropped from 115 MH/s to about 80 MH/s, but the card reports consuming 70W more than in version v0.5.2.0 stable. So the reported "Eff kH/J" in OCTune is about halved. Tried a few settings, but couldn't raise the hashrate to more than 80MH/s, so downgraded back to v0.5.2.0 stable to keep a satisfying hashrate. For it is an RTX3090 it can't be a LHR issue, so I haven't touched these settings in OCTune. You should definitively check this out.

Killua

**Comment by mikeroygray** [comment]
I don't have this behavior on my 309ü. It's still doing the same ca. 120 mh/s as before. Two card rig, the other is a 3080 ti.

**Comment by fmiqbal** [comment]
I have 3070 and it make `dwm` hog more GPU than usual, so it make nicehash has lower hashrate. Also when I launch bluestacks, 5.2.0 gave me like -5 MH/s drop, 5.3.0 give me like -20 MH/s. I haven't try to isolate the issue though, it maybe caused by different nvidia driver, but when I see this issue in board just make me instantly move to 5.2.0 again and make it "normal" again

**Comment by Dohtar1337** [comment]
Please use 472.xx drivers and the latest RC 0535 version of QM
