### ISSUE TITLE
The fans do not start.

### ISSUE THREAD

**Issue by kadiev75** [nicehash/NiceHashQuickMiner#738]
I have a rig with 8 cards: (4 x AMD Radeon RX 6700 XT Subvendor: AMD) and (4 x AMD Radeon RX 6700 XT Subvendor: ASUS)
After setup, the (4 x AMD Radeon RX 6700 XT Subvendor: ASUS) fans do not start in any way while the  (4 x AMD Radeon RX 6700 XT Subvendor: AMD) is working properly.

just run the miner and you will see that the fans do not start. Everyone works with the t-rex in the same configuration.

I expect you to correct the problem and be able to control the fans on (4 x AMD Radeon RX 6700 XT Subvendor: ASUS)

Version number 0.5.3.3 RC

AMD driver : 21.11.3

I have a rig with 8 cards: (4 x AMD Radeon RX 6700 XT Subvendor: AMD) and (4 x AMD Radeon RX 6700 XT Subvendor: ASUS)

**Comment by teejabadeej** [comment]
Same issue with 8x 6700XT, all ASUS cards. I noticed that Excavator was giving a message about shutting down MSI Afterburner when it started. I have no configuration in Afterburner, I'm only using it for monitoring temps and things more closely. If I open Afterburner again after Excavator launches, the fans will start working again. Not sure exactly what is causing this, but this has been a usable workaround for me until the issue is resolved.

**Comment by Dohtar1337** [comment]
Solved in the upcoming release
