### ISSUE TITLE
[OPTIMIZATION] 3080ti

### ISSUE THREAD

**Issue by rayvearn** [nicehash/NiceHashQuickMiner#761]
There's no optimization profiles for the 3080ti at the moment. Right now, i just averaged the profiles of the 3090 and 3080 and tweaked upward a bit since it's more similar to a 3090. It would be great however, to see actual optimization profiles for it, especially as tweaking it is hard since the LHR locks up hard if you mess with the clocks too much.

**Comment by J3G0** [comment]
Agreed. I used to run the previous stable version with +-64 MH/s on efficient. This was nearly silent to mine with VRAM temp staying at 86 degrees. Now efficient doesn't work because it can not find a stable LHR unlock. 

Using Lite it works with the fans at 100%, VRAM at 96/98 degrees and does around 80 MH/s, while using almost 300W.

So for me this update is a downgrade.

**Comment by 3uPh0riC** [comment]
Same issue here, I just  shut off the miner. I also cant seem to rollback to previous version easily. Ill probably try some other miner or try do a clean install of the old version

**Comment by Dohtar1337** [comment]
Profiles for 3080ti are online.
