### ISSUE TITLE
[QUESTION]  RX 6800 and Wattman

### ISSUE THREAD

**Issue by ben1628** [nicehash/NiceHashQuickMiner#797]
I'm trying to use Quickminer v0.5.3.6 RC with this Radeon RX6800 for the very first time last night but it crashed may be 8 hours later.

1/ Should I use Radeon Wattman at all, previously I was using Phoenix miner and needed to set this to Manual and turn on Fast timing!

2/ In OCTune, which section should I used, there is a AMD section, should I use it? in Wattman, it was set to  VRAM 2140, Clock 1200 and voltage at 2140.

4/ How about fan setting, I think it crashes because it gets too hot. it is running at 129 Watt

Thanks.

**Comment by Dohtar1337** [comment]
1 AMD QM does not support setting fast timings yet. This is something we will look into in the future

2 You should use AMD overclocking section

4 You should set fan speed via OCtune. It is known bug when fan controller might not work sometimes. If you set manually profile, the issue is not present anymore
https://www.nicehash.com/blog/post/modify-existing-optimization-profiles

**Comment by Dohtar1337** [comment]
No response. Closing.
