### ISSUE TITLE
[BUG] Currently isn't working on 2 of my 3060ti's and has no lhr unlock effect and also constantly says "fail" every few seconds

### ISSUE THREAD

**Issue by KazeNerve** [nicehash/NiceHashQuickMiner#820]
**Describe the bug**
When starting Quickminer it does all of the necessary things and makes the unlock ratio 55/100% but
my hashrate stays at 30mh for both cards and also shows a "fail" message every few seconds on the left side
of the screen and I seem to be unable to fix it

**Expected behavior**
I expected the gpus to become unlocked and to run and produce full hashrate

**Screenshots**
![image](https://user-images.githubusercontent.com/105129301/167270661-2e9b6069-173a-4659-8320-6a376f53ef00.png)

**Version affected (please complete the following information):**
 - Version number [e.g. 0.4.5.5] v0.5.4.0
 - RC or STABLE? RC

**NVIDIA driver version**
Which one do you use? 472.84

**Hardware**
Describe GPUs used and how are GPUs connected to the motherboard.
CPU? Both gpus are LHR 3060 ti's and they are connected directly to the motherboard
and cpu is a AMD-FX-8350

**Additional context**

**Comment by moops44** [comment]
Open OCTune 
Check OPTIMIZE profile and set it to whatever Profil u want , and click Apply All where its highlighted in yellow

**Comment by danielantcliffe** [comment]
Hi, I have the same issue.
My rig setup is 1x 3070ti, 1x 3060ti, 4x 1660ti.

Only when two both 30 series cards are installed in the mining frame at the same time, the hash rate for the 3070ti does not unlock and stays at 45 instead of 75 as expected.

Screenshot includes the full hash rate working together with the 1660Ti cards.
Please can NiceHash fix this bug so I can reinstall the 3060ti to the frame and have an additional 60MH :)
![Capture](https://user-images.githubusercontent.com/105131393/167272783-95cac262-aa83-4edc-aac4-7c86e3651b49.PNG)

**Comment by nushydude** [comment]
If you are on 472.xx, you will see this Fail message. If you are on the latest drivers, you won't. Just observation. I don't know what the impact of it is.

**Comment by Dohtar1337** [comment]
This issue should be solved in the upcoming release. Please follow NHQM updates and see if the next release solves the issue for you.
