### ISSUE TITLE
Fan problem [BUG] 

### ISSUE THREAD

**Issue by Elar74** [nicehash/NiceHashQuickMiner#838]
FAN

I upgrade from 0.5.3.3 the new version quickminer
Since then, the fan has been working strangely.
So far, it has cooled the processor evenly.
now "back and forth".
FAN Stop - starts, spins up completely - stop again.
and it repeats itself.

**Version affected (please complete the following information):**
 - Version number [e.g. 0.4.5.5]   0.5.3.6  and 0.5.4.0
 - RC or STABLE?  Both

**NVIDIA driver version**
512.59

**Hardware**
Nvidia Geforce RTX 2070

**Comment by rickyricks7** [comment]
I am having the same issue, just started today.

**Comment by MelodyYang** [comment]
same problem as mine。 0.5.3.6 STABLE and 0.5.4.0 RC

**Comment by wallaceaskew** [comment]
Same issue.
Downgrading back to v0.5.3.3 resolved the issue.


Driver version 512.59  RTX 3090 FE

**Comment by Elar74** [comment]
> Same issue. Downgrading back to v0.5.3.3 resolved the issue.
> 
> Driver version 512.59 RTX 3090 FE

At first I wanted to do the same
But even though I downloaded 0.5.3.3.3, it only offered the two new versions for installation

**Comment by wallaceaskew** [comment]
You have to download the zip version.

**Comment by andrew2005** [comment]
Same problem here. I upgraded versions because I was experiencing this [Anti-LHR](https://www.nicehash.com/blog/post/psa-mining-with-nvidia-drivers-v511-23-or-newer) issue on my 3090 which isn't LHR. 

Fans constantly spinning up and down. OCTune or API Smartfan settings (smartfanset or device.smartfan.set.advanced method) don't work properly anymore. Setting fixed fan to 100% doesn't work. Setting minimum and maximum fan speed doesn't work. Excavator logs change in fan profile but it just doesn't work.  

I play games so don't want to roll back Nvidia driver. Both latest stable and RC had same issue.

**Comment by Chien80920** [comment]
> > 同樣的問題。降級回 v0.5.3.3 解決了這個問題。
> > 驅動程序版本 512.59 RTX 3090 FE
> 
> 起初我也想這樣做 但是即使我下載了0.5.3.3.3，它也只提供了兩個新版本進行安裝

https://github.com/nicehash/NiceHashQuickMiner/tree/main/checksums

**Comment by Dohtar1337** [comment]
We are working on this.

**Comment by Dohtar1337** [comment]
This issue should be solved in the upcoming release. Please follow NHQM updates and see if the next release solves the issue for you.
