### ISSUE TITLE
[BUG] can't unlock this card, restart if you want to retry (3060 v2 12gb - v0.5.4.1 RC)

### ISSUE THREAD

**Issue by saulob** [nicehash/NiceHashQuickMiner#850]
Still not unlocking my card. It did not unlock on 0.5.4.0 too.
There's a new error message: "can't unlock this card, restart if you want to retry"

My card: Gigabyte 3060 Eagle LHR 12GB (GV-N3060EAGLE-12GD REV 2.0)
Windows 10 21H2, driver: 512.59

0.5.4.0 and 0.5.4.1 is slower than 0.5.3.6 stable for my card :(

![2022-05-12_13-19-08](https://user-images.githubusercontent.com/3660977/168122452-635211fa-9671-4340-b1ae-50e5f4b51086.png)

![2022-05-12_13-17-30](https://user-images.githubusercontent.com/3660977/168122469-685d3cb0-bd14-4cce-b95e-ecb24c8e8e21.png)

**Comment by rodrigoext** [comment]
Same here, but only one of my 3060's.


![image](https://user-images.githubusercontent.com/2568433/168307296-52a4f058-2520-4ec3-a50d-afac98ecdd7b.png)

![image](https://user-images.githubusercontent.com/2568433/168307604-6ba6cc40-25c0-421a-9f3f-2e1f48306ed3.png)

**Comment by chiekku** [comment]
Same issue with two of my GIGABYTE RTX 3060 12GB (GV-N3060GAMING OC-12GD (rev. 2.0) (LHR))

The two that fail to unlock show up in GPU-Z as GA104, while the rest that can be unlocked are GA106.  Not sure why it would matter, but one thing I noticed is they have Samsung memory instead of Hynix, along with different fill rates and other stats. 

Can anyone else confirm their locked cards are GA104?

**Comment by saulob** [comment]
Mine is GA104 too
Gigabyte 3060 Eagle LHR 12GB (GV-N3060EAGLE-12GD REV 2.0)

**Comment by rodrigoext** [comment]
It seems the issue is with GA104 version
![image](https://user-images.githubusercontent.com/2568433/168532691-29d80f0c-4a50-4849-897c-ca4a825776f4.png)

I have another Zotac 3060 (GA106 LHR) working fine with 100% LHR unlock
![image](https://user-images.githubusercontent.com/2568433/168532919-af6bf151-3880-49b3-8e56-d41689d0a850.png)

**Comment by Dohtar1337** [comment]
NiceHashMiner/plugins/ash89asdj9-asdo8/bins/17.6/tukej notri
