### ISSUE TITLE
[BUG] LHR not unlocked with nvidia 512.95

### ISSUE THREAD

**Issue by mntorq** [nicehash/NiceHashQuickMiner#875]
**Describe the bug**
Low hash rate (60MH/s) on 3080Ti

**To Reproduce**
Install nvidia driver
Use QM 

**Expected behavior**
unlocked hash rate (prev driver version was 108-115MH/s)

**Version affected (please complete the following information):**
 - 5.4.2 RC

**NVIDIA driver version**
 512.95

**Hardware**
3080Ti

**Comment by FireDragonix** [comment]
Describe the bug
Low hash rate (50 - 60MH/s) on 3080 - High profile

To Reproduce
Install nvidia driver
Use QM

Expected behavior
unlocked hash rate (prev driver version was 100-120MH/s) Was using NHQM 5.4.0

Version affected (please complete the following information):

5.4.2 RC
NVIDIA driver version
512.95

Hardware
3080

**Comment by blin25** [comment]
Yes .  After Install new Nvidia driver 512.95 / Hash Rate 50%  on 3070 Ti ~ 42 MH/s
5.4.2 RC
NVIDIA driver version
512.95
unlocked hash rate Broken от new driver ..

**Comment by 19Micke71** [comment]
> Yes . After Install new Nvidia driver 512.95 / Hash Rate 50% on 3070 Ti ~ 42 MH/s 5.4.2 RC NVIDIA driver version 512.95 unlocked hash rate Broken от new driver ..

Same issue here & changing to lite, medium or high OC makes no difference to hashrate.

**Comment by thecute** [comment]
Also experiencing same behaviour after installing latest NVIDIA drivers 512.95.

Describe the bug
Low hash rate (60MH/s) on 3080 12GB LHRv3

To Reproduce
Install NVIDIA driver
Use QM

Expected behaviour
unlocked hash rate (prev driver version was 96-105 MH/s)

Version affected (please complete the following information):

    5.4.2 RC

NVIDIA driver version
512.95

Hardware
3080 12GB LHRv3
[exported_logs_05_25_2022.zip](https://github.com/nicehash/NiceHashQuickMiner/files/8772783/exported_logs_05_25_2022.zip)

**Comment by hwatt2** [comment]
Same Issue here.

Nvidia Driver 512.95 QuickMiner v0.5.4.2 RC roughly half usual hash rate on my RTX3060 gen1 (see also #869).

**Comment by thecute** [comment]
https://www.nicehash.com/blog/post/psa-full-lhr-unlock-does-not-work-with-nvidia-512-95-driver
